[development]
address = "0.0.0.0"
port = 80
keep_alive = 0
log = "normal"
workers = 10
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80
keep_alive = 0
log = "normal"
workers = 10
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
keep_alive = 0
log = "critical"
workers = 10
limits = { forms = 32768 }
